// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using TitanicSurvivalML.Model;

namespace TitanicSurvivalML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\MyFolder\Labs\MLnet\MLNetLearningRepo\TitanicSurvival\TitanicMLApp\train-filtered-rd.csv";

        static void Main(string[] args)
        {
            bool terminate = false;

            do
            {
                ModelInput sampleData = new ModelInput();

                Console.Write("Enter ticket class (1, 2, 3):");
                sampleData.Pclass = Convert.ToInt32(Console.ReadLine());
                Console.Write("Enter gender (1 - male, 2 - female):");
                sampleData.Gender_Normalized = Convert.ToInt32(Console.ReadLine());
                Console.Write("Enter age range  (1-10):");
                sampleData.Age_Notmalized = Convert.ToInt32(Console.ReadLine());
                Console.Write("Enter fare range  (1-10):");
                sampleData.Fare_Notmalized = Convert.ToInt32(Console.ReadLine());

                ModelOutput predictedResult = ConsumeModel.Predict(sampleData);
                Console.WriteLine("The trained model predicts you " + (predictedResult.Prediction==true?"survived":"did not survice"));

                Console.WriteLine("Press any key to make another prediction or <return> to terminate:");
                string response = Console.ReadLine();
                terminate = String.IsNullOrEmpty(response);

            }
            while (!terminate);
        }

    } 
    
}
